name: Process code submission

on:
  repository_dispatch:
    types: code-submission
  workflow_dispatch:

jobs:
  main:
    name: Main job
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12'
    - name: Install Github actions
      run: |
        npm install --no-package-lock --no-save @actions/core
    - name: Process submission 
      run: |
        node actions/process-code-submission.js
    - name: Create Pull Request
      uses: peter-evans/create-pull-request@v3
      with:
        title: '[Code submission] ${{ env.NAME }} by ${{ env.AUTHOR }}'
        body: |
          ${{ env.LINES }} lines written in ${{ env.LANGUAGE_NAME }}
        delete-branch: true
        branch-suffix: short-commit-hash
        
