name: Stats Updater

on:
  repository_dispatch:
    types: update-stats
  workflow_dispatch:

jobs:
  process-stats:
    name: Process Stats
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
      with:
        token: ${{ secrets.GH_PERSONAL_TOKEN }}
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12'
    - name: Install Github actions
      run: |
        npm install --no-package-lock --no-save @actions/core
    - name: Process stats
      run: |
        node actions/process-stats-update.js
    - name: Commit and push changes to master
      uses: stefanzweifel/git-auto-commit-action@v4.6.0
      with:
        commit_message: Stats update
        commit_user_name: Update Stats Action
        commit_user_email: bot@github.com
        commit_author: Bot <bot@github.com>
        
